### ISSUE TITLE
DLNA DMR can´t find Libratone Zipp 2 device

### ISSUE THREAD

**Issue by marrobHD** [StevenLooman/home-assistant-dlna-dmr#10]
It cant discover my Libratone Zipp 2. How can I get the Port. My app tells me that it is: http://192.168.178.52:49152/description.xml but if I open the website with the browser it shows me the Error:
This page contains the following errors:
error on line 19 at column 15: Encoding error
Below is a rendering of the page up to the first error.
1 0 urn:schemas-upnp-org:device:MediaRenderer:1 DMR-1.50 LibratoneZipp334A3D Libratone http://www.libratone.com/ Libratone Zipp LTH 300 http://www.libratone.com/home/products/zipp/#intro uuid:e89ba2a2-1e37-4ed2-925d-2c6fa72fde59

Thanks for help

**Comment by StevenLooman** [comment]
The URL you're giving is the URL required for the `dlna_dmr`-component. In
your case, your configuration-entry would be as follows:

media_player:
  - platform: dlna_dmr
    url: http://192.168.178.52:49152/description.xml

See https://www.home-assistant.io/components/media_player.dlna_dmr/ for
more information.

You can also explicitly enable discovery of this component via the
`discovery`-component. This saves you the trouble (or at least is should)
of figuring out the URL yourself. You can enable the discovery as follows:

discovery:
  enable:
    - dlna_dmr

See https://www.home-assistant.io/components/discovery/ for more
information.

Hope this answers your question.
