### ISSUE TITLE
GGMM E5 Wireless Speakers - Working

### ISSUE THREAD

**Issue by westerncanada** [StevenLooman/home-assistant-dlna-dmr#6]
Firstly, thanks for this.  I got the custom component working easily.

I'm happy to report that the GGMM E5 Wireless Speakers (I got of amazon.ca for a deal) work very well.

I'm using them for TTS and Spotify.

Let me know if I can get you any info about my setup.

Here are the notes for what I did:

Created a folder called beta in home assistant home folder
mkdir -p /home/homeassistant/beta
cd /home/homeassistant/beta

did a git clone of your repository
git clone https://github.com/StevenLooman/home-assistant-dlna-dmr.git

mkdir -p /home/homeassistant/.homeassistant/custom_components/media_player
This created the folder custom_components in the config folder
it then created the folder media_player inside that folder

cd /home/homeassistant/.homeassistant/custom_components/media_player
from there I symlinked the dlna_dmr.py and setup.py 
ln -s ../../../beta/home-assistant-dlna-dmr/home_assistant_dlna_dmr/dlna_dmr.py
ln -s ../../../beta/home-assistant-dlna-dmr/setup.py
```

Added the following to the media_player section
  - platform: dlna_dmr
    url: http://192.168.XX.YY:49152/description.xml
    name: Speaker01
```

Did some setup of the Spotify component, and the speaker showed up in the list right away.
I also did some TTS testing, however I cannot use the spotify TTS for this speaker, I had to create a separate media_player device for that.

All in all works well enough for me.

Thanks again,

**Comment by StevenLooman** [comment]
Great, thank you for reporting!

The component (albeit a bit changed after reviews) is in the process of being integrated into Home Assistant itself, via [this pullrequest](https://github.com/home-assistant/home-assistant/pull/14749).

Can you report your device works there as well, without the installation notes?

Again, thank you for testing and reporting!
