### ISSUE TITLE
HA Documentation a bit spotty...

### ISSUE THREAD

**Issue by arretx** [StevenLooman/home-assistant-dlna-dmr#8]
I'm wondering, for my Aquos television, what I would use for the media_player's URL configuration variable, which seems to be a required variable.

If the TV is on 192.168.2.2, would I simply use `http://192.168.2.2`?

Accessing this address through a browser results in no response.

**Comment by StevenLooman** [comment]
Be sure to use not use this version of the dlna_dmr-component, but use the version integrated into home assistant itself.

Please see #7 on how to retrieve the url. Preferably, you would use discovery, however (see also #7)
